const express = require("express");
const route = express.Router();

route.use("/admin", require("./auth"));
route.use("/role", require("./role"));
route.use("/blog", require("./blog"));
route.use("/faq", require("./faq"));
route.use("/faqTypes", require("./faqTypes"));
route.use("/imageGallery", require("./imageGallery"));
route.use("/videoGallery", require("./videoGallery"));
route.use("/videoGalleryCategory", require("./videoGalleryCategory"));
route.use("/imageGalleryCategory", require("./imageGalleryCategory"));
route.use("/airport", require("./airport"));
route.use("/inquiry", require("./inquiry"));
route.use("/packages", require("./packages"));
route.use("/packagesBoxDetails", require("./packagesBoxDetails"));
route.use("/packagesPricing", require("./packagePricing"));
route.use("/packagesAdditionalInfo", require("./packageAdditionalInfo"));
route.use("/packagesIncludes", require("./packageIncludes"));
route.use("/reviews", require("./reviews"));
route.use("/transaction", require("./transaction"));
route.use("/defaultContent", require("./defaultData"));
route.use("/packageIcon", require("./packageIcon"));
route.use("/banner", require("./banner"));
route.use("/email", require("./email"));
route.use("/service", require("./service"));
route.use("/service-type", require("./serviceType"));
route.use("/image-banner", require("./ImageBanner"));
route.use("/country", require("./country"));
route.use("/cheque-payment", require("./chequePayment"));
route.use("/mobile-cms", require("./appCmsPage"));
route.use("/applications", require("./applicationManagement"));
route.use("/payments", require("./paymentManagement"));
route.use("/app-users", require("./appUserManagement"));
route.use("/notifications", require("./notificationManagement"));
module.exports = route;
